export const CHOOSE_BACKGROUND = "CHOOSE_BACKGROUND";
export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";
export const SET_USER = "SET_USER";
export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const SET_ARTICLE_ON_EDIT = "SET_ARTICLE_ON_EDIT";